#!/bin/bash -login
#PBS -l walltime=150:00:00,nodes=01:ppn=4,mem=400gb
#PBS -q main
#PBS -M qingpeng@gmail.com
#PBS -m abe
#PBS -A ged-intel11

module load khmer
module load screed
cd /mnt/scratch/tg/qingpeng/Iowa_Data_From_Adina/gpgc-trimmed-reads/iowa-corn
python /mnt/home/qingpeng/bin/khmer/scripts/load-into-counting.py --ksize 20 --n_hashes 4 --hashsize 48e9 iowa-corn-all-small.ht iowa-corn-all.fasta


cd /mnt/scratch/tg/qingpeng/2004-gpgc/run
python /home/qingpeng/Dropbox/Work/Manuscript/2014-gpgc/pipeline/calc-coverage-matrix.py /mnt/scratch/tg/qingpeng/Iowa_Data_From_Adina/gpgc-trimmed-reads/iowa-prairie/iowa-prairie-all-small-new.ht /mnt/scratch/tg/qingpeng/Iowa_Data_From_Adina/gpgc-trimmed-reads/iowa-corn/iowa-corn-all-small.ht /mnt/scratch/tg/qingpeng/Iowa_Data_From_Adina/gpgc-trimmed-reads/iowa-prairie/iowa-prairie-all.fasta /mnt/scratch/tg/qingpeng/Iowa_Data_From_Adina/gpgc-trimmed-reads/iowa-corn/iowa-corn-all.fasta full_corn_prairie_coverage_matrix.out

